spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://35.185.146.34:3306/user?useUnicode=true&characterEncoding=UTF-8&useSSL=true
#    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=UTF-8
    username: alison
#    username: root
    password: 123456
  http:
    multipart:
      max-request-size: 256KB
      max-file-size: 256KB
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  thymeleaf:
    cache: false
    enabled: true
server:
  port: 8082
mybatis:
  type-aliases-package: com.code.Entity
  mapper-locations: classpath:Mapper/*.xml


logging:
  level:
    com:
      code:
        mapper:
          UserMapper: debug

